[package]
name = "typedb_test"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
typedb-driver = "3.0.5"
async-std = { version = "1.12", features = ["attributes"] }
futures = "0.3"

[[bin]]
name = "main"
path = "main.rs"

[[bin]]
name = "persistence_check"
path = "obsolete/persistence_check.rs"
